import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import Loading from "./loading";
import Header from "@/components/share/header/Header";
import Footer from "@/components/share/footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense fallback={<Loading />}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-7xl ml-[auto] mr-[auto]`}
        >
          <ApolloWrapper>
            <Header />
            <main className="font-[family-name:var(--font-geist-sans)]">
              {children}
            </main>
            <Footer />
            <div id="portal-root"></div>
          </ApolloWrapper>
        </body>
      </Suspense>
    </html>
  );
}
